version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - REDIS_ADDR=redis:6379
      - ENVIRONMENT=development
    depends_on:
      - mongodb
      - redis
    volumes:
      - .:/app
    networks:
      - dictionary-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - dictionary-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dictionary-network

volumes:
  mongodb_data:
  redis_data:

networks:
  dictionary-network:
    driver: bridge